### ISSUE TITLE
Tax rate input showing $ if blank value

### ISSUE THREAD

**Issue by kcwebmedia** [angelleye/paypal-pos#21]
When there is a blank default tax rate set in the config file, then the tax rate has a default dollar sign $, which is throwing off the grand total calculation.
* The tax rate input field needs to be set on 'init' to not have a symbol or default set as for the autoNumeric js init.

**Comment by kcwebmedia** [comment]
* Needs to lock down that input field to only digits.

**Comment by angelleye** [comment]
The reason it was putting a $ in there is because you had that set in the shorthand if/else statement that was setting the value of the field based on the config setting.  I adjusted this in #14 already.
