### ISSUE TITLE
Donate Button

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-pos#7]
I would like to add a Donate button to the menu bar on the left.  We can leave it in the top, right menu too, but I'd like a larger one in that left side menu.

**Comment by kcwebmedia** [comment]
What will the donate URL be?

**Comment by angelleye** [comment]
https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=PPHP4UKDUTZYS
